/**
 * The user-facing heading for each section kind — curated words, never the internal id.
 *
 * The heading maker used to title-case the section kind, so the internal identifier WAS the
 * heading by construction ("Point Inventory Or Decomposition", "Source Signal Guidance"). Every
 * kind the pipeline can plan now has a display name a developer can read at a glance.
 *
 * Two rules shaped the words, both load-bearing:
 *   - A heading is scanned as body text by the safety validators. A display name therefore never
 *     introduces a risk or execution word the kind's own id does not already carry — otherwise a
 *     title could change when the confirmation line fires. Pinned by test.
 *   - The vocabulary is open (preset lists add kinds), so an unmapped kind title-cases rather
 *     than crashing; the completeness gate makes an unmapped addition fail the build.
 *
 * Wording is owner-approved (2026-08-25) and lands byte for byte.
 */
export const SECTION_DISPLAY_NAMES_V1: Readonly<Record<string, string>> = {
  // Planner kinds.
  original_request_or_goal: 'My original request (verbatim)',
  context_and_constraints: 'Context and constraints',
  acceptance_or_output_expectation: 'What done looks like',
  verification_or_test_plan: 'How to verify',
  reproduction_or_evidence: 'Reproduction and evidence',
  behavior_preservation: 'What must keep working',
  risk_safety_or_confirmation: 'Risk, safety and confirmation',
  project_grounding_facts: 'Project facts',
  requirement_source_state: 'Requirement grounding',
  handoff_or_sequence_candidate: 'Hand-off and sequencing',
  point_inventory_or_decomposition: 'The separate points',
  uncertainty_or_clarification: 'Open questions',
  finding_format: 'How to report findings',
  source_signal_guidance: 'Best practices and standards',
  // Preset kinds planned at every level.
  affected_behavior_tests: 'Tests for the affected behaviour',
  affected_surface: 'Affected surface',
  approach_or_steps: 'Approach and steps',
  assumptions_open_questions: 'Assumptions and open questions',
  auth_config_boundary: 'Auth and config boundary',
  backup_dry_run: 'Backup and dry run',
  backward_compatibility_boundary: 'Backward compatibility boundary',
  baseline_current_metric: 'Current baseline metric',
  baseline_current_output_proof: 'Proof of the current output',
  baseline_metric_state: 'Baseline metric state',
  behavioral_assertion: 'Behavioural assertion',
  behavioral_coverage: 'Behavioural coverage',
  boundary_map: 'Boundary map',
  call_path_boundary: 'Call path boundary',
  changelog_breaking_change_state: 'Changelog and breaking-change state',
  code_diff_target: 'Code diff target',
  compatibility: 'Compatibility',
  config_diff_or_evidence: 'Config diff or evidence',
  confirmation_need: 'Confirmation needed',
  contract_matrix_testing: 'Contract matrix testing',
  contract_test_expectation: 'Contract test expectation',
  contracts_data_flow: 'Contracts and data flow',
  current_behavior: 'Current behaviour',
  current_new_versions: 'Current and new versions',
  current_test_weakness: 'Current test weaknesses',
  data_integrity_verification: 'Data integrity verification',
  data_schema_source_of_truth: 'Data schema source of truth',
  data_shape_change: 'Data shape change',
  dependency_order: 'Dependency order',
  desired_extension: 'Desired extension',
  docs_config_alignment: 'Docs and config alignment',
  evidence_preservation: 'Evidence preservation',
  evidence_request: 'Evidence request',
  exact_steps_request: 'Exact steps request',
  expected_actual_state: 'Expected vs actual',
  fit_gap_checklist: 'Fit and gap checklist',
  fixture_mock_context: 'Fixture and mock context',
  fixture_mock_quality: 'Fixture and mock quality',
  hypothesis_isolation: 'Hypothesis isolation',
  impact_severity: 'Impact and severity',
  incremental_steps: 'Incremental steps',
  intended_work_preservation: 'Preserving intended work',
  interfaces_modules: 'Interfaces and modules',
  isolation_hypothesis: 'Isolation hypothesis',
  last_known_good_current_behavior: 'Last known good vs current behaviour',
  migration_order: 'Migration order',
  mitigation_boundary: 'Mitigation boundary',
  narrow_fix_boundary: 'Narrow fix boundary',
  no_secret_leakage: 'No secret leakage',
  non_secret_config_names: 'Non-secret config names',
  one_module_layer_at_a_time: 'One module or layer at a time',
  pass_fail_comparison: 'Pass and fail comparison',
  pre_change_snapshot_baseline: 'Pre-change snapshot baseline',
  problem_statement: 'Problem statement',
  profiling_measurement_path: 'Profiling and measurement path',
  recent_change: 'Recent change',
  reference_search: 'Reference search',
  regression_risk: 'Regression risk',
  repeatability_attempts: 'Repeatability attempts',
  request_response_sample: 'Request and response sample',
  request_response_schema: 'Request and response schema',
  residual_risk: 'Residual risk',
  review_scope: 'Review scope',
  review_target_scope: 'Review target and scope',
  risk_statement: 'Risk statement',
  rollback_recovery: 'Rollback and recovery',
  rollout_steps: 'Rollout steps',
  scope_non_goals: 'Scope and non-goals',
  security_surface: 'Security surface',
  smallest_hot_path_change: 'Smallest hot-path change',
  smallest_repro_request: 'Smallest repro request',
  source_of_truth_state: 'Source of truth state',
  stable_fixtures: 'Stable fixtures',
  stack_trace_or_error_state: 'Stack trace or error output',
  status_schema_contract: 'Status and schema contract',
  supported_clients_versions_platforms: 'Supported clients, versions and platforms',
  system_boundaries: 'System boundaries',
  target_artifact: 'Target artifact',
  task_order_dependencies: 'Task order and dependencies',
  test_command_output: 'Test command output',
  test_target: 'Test target',
  threat_input_auth_secret_data_checks: 'Threat, input, auth, secret and data checks',
  tradeoffs: 'Trade-offs',
  triggering_input_state: 'Triggering input and state',
  unused_code_proof: 'Proof the code is unused',
  user_journey_screen_state: 'User journey and screen state',
  version_environment_contrast: 'Version and environment contrast',
  workload_or_bottleneck_evidence: 'Workload or bottleneck evidence',
  workload_or_input_size: 'Workload or input size',
  // Preset kinds planned at the thorough level.
  alternatives: 'Alternatives',
  approval_checkpoint: 'Approval checkpoint',
  assertion_gap_check: 'Assertion gap check',
  assertion_quality_check: 'Assertion quality check',
  assertion_quality_review: 'Assertion quality review',
  baseline_tests: 'Baseline tests',
  before_after_expectation: 'Before and after expectation',
  before_after_measurement: 'Before and after measurement',
  before_after_verification: 'Before and after verification',
  blocked_decisions: 'Blocked decisions',
  callsite_matrix: 'Call-site matrix',
  change_isolation: 'Change isolation',
  checklist_focus: 'Checklist focus',
  client_impact_review: 'Client impact review',
  compatibility_matrix: 'Compatibility matrix',
  config_matrix: 'Config matrix',
  configuration_contract_check: 'Configuration contract check',
  contract_matrix_tests: 'Contract matrix tests',
  contract_test_plan: 'Contract test plan',
  coupling_interface_review: 'Coupling and interface review',
  cutover_validation: 'Cutover validation',
  data_integrity_checks: 'Data integrity checks',
  decision_criteria: 'Decision criteria',
  deeper_checks: 'Deeper checks',
  definition_of_done: 'Definition of done',
  dependency_risk_review: 'Dependency risk review',
  dependency_security_check: 'Dependency security check',
  docs_drift_check: 'Docs drift check',
  edge_case_fit: 'Edge-case fit',
  edge_cases: 'Edge cases',
  environment_reproduction_matrix: 'Environment reproduction matrix',
  evidence_capture_list: 'Evidence capture list',
  exception_path_verification: 'Exception path verification',
  expand_migrate_contract: 'Expand, migrate, then contract',
  feature_flag_plan: 'Feature flag plan',
  fix_boundary: 'Fix boundary',
  fixture_coupling_review: 'Fixture coupling review',
  fixture_stability_review: 'Fixture stability review',
  hot_path_isolation: 'Hot-path isolation',
  hypothesis_order: 'Hypothesis order',
  incident_regression_checks: 'Incident regression checks',
  incident_response_notes: 'Incident response notes',
  integration_checkpoint: 'Integration checkpoint',
  integration_regression_checks: 'Integration regression checks',
  interaction_state_matrix: 'Interaction and state matrix',
  layout_regression_checks: 'Layout regression checks',
  load_profile_notes: 'Load profile notes',
  local_ci_repeat_matrix: 'Local and CI repeat matrix',
  manual_browser_checks: 'Manual browser checks',
  measurement_plan_review: 'Measurement plan review',
  migration_notes: 'Migration notes',
  migration_rehearsal: 'Migration rehearsal',
  milestone_size: 'Milestone size',
  module_sequence_plan: 'Module sequence plan',
  nearby_behavior_checks: 'Nearby behaviour checks',
  nearby_regression_checks: 'Nearby regression checks',
  no_feature_change_boundary: 'No feature-change boundary',
  no_unrelated_change_boundary: 'No unrelated-change boundary',
  non_secret_validation_steps: 'Non-secret validation steps',
  observable_outcome: 'Observable outcome',
  per_path_test_plan: 'Per-path test plan',
  performance_regression_guard: 'Performance regression guard',
  pin_path: 'Pin the path',
  post_change_monitoring: 'Post-change monitoring',
  post_cleanup_regression: 'Post-cleanup regression',
  postmortem_followup: 'Postmortem follow-up',
  race_isolation_plan: 'Race isolation plan',
  reader_handoff_notes: 'Reader hand-off notes',
  regression_guard: 'Regression guard',
  regression_notes: 'Regression notes',
  regression_value: 'Regression value',
  release_readiness_checks: 'Release readiness checks',
  relevant_suite_rerun: 'Relevant suite rerun',
  remediation_options: 'Remediation options',
  removal_boundary: 'Removal boundary',
  repeated_verification_matrix: 'Repeated verification matrix',
  repro_reduction_plan: 'Repro reduction plan',
  requirement_mapping: 'Requirement mapping',
  restore_service_plan: 'Restore service plan',
  retry_rate_limit_notes: 'Retry and rate-limit notes',
  risk_review: 'Risk review',
  risk_summary: 'Risk summary',
  rollback_drill: 'Rollback drill',
  rollback_test_plan: 'Rollback test plan',
  schema_diff_review: 'Schema diff review',
  stabilization_boundary: 'Stabilisation boundary',
  stakeholder_context: 'Stakeholder context',
  stop_before_fix_instruction: 'Stop and report before fixing',
  suggested_changes: 'Suggested changes',
  suggested_fixes: 'Suggested fixes',
  targeted_checks: 'Targeted checks',
  targeted_regression_tests: 'Targeted regression tests',
  targeted_rerun: 'Targeted rerun',
  test_gap_review: 'Test gap review',
  versioning_risk: 'Versioning risk',
  vertical_slice_boundaries: 'Vertical slice boundaries',
};

/** Title-case an unmapped kind: the open vocabulary must never crash a render. */
function titleCaseKind(sectionKind: string): string {
  return sectionKind.split('_').filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/** The heading for a section kind — curated words, with the title-case fallback for unmapped kinds. */
export function promptEnhancementSectionDisplayNameV1(sectionKind: string): string {
  return SECTION_DISPLAY_NAMES_V1[sectionKind] ?? titleCaseKind(sectionKind);
}
