// The frozen labelled fixture set shared by the sensitive-action test suites: 45 prompts,
// 20 'confirm' (a risky action is genuinely proposed) and 25 'quiet' (a risky word in a
// harmless role), plus today's real body-level firing sets on the deterministic fixture
// context. Data only — no behaviour lives here.
export interface SensitiveActionFixtureRow { id: number; expect: 'confirm' | 'quiet'; prompt: string }
export const SENSITIVE_ACTION_FIXTURE_ROWS: readonly SensitiveActionFixtureRow[] = [
  { id: 1, expect: 'confirm', prompt: 'delete the old migrations folder, we don\'t need any of it' },
  { id: 2, expect: 'confirm', prompt: 'wipe the uploads directory and start fresh' },
  { id: 3, expect: 'confirm', prompt: 'run the migration against the production database tonight' },
  { id: 4, expect: 'confirm', prompt: 'truncate the events table, it has grown too big' },
  { id: 5, expect: 'confirm', prompt: 'upgrade every dependency to latest and update the lockfile' },
  { id: 6, expect: 'confirm', prompt: 'npm install the new charting package and wire it in' },
  { id: 7, expect: 'confirm', prompt: 'rotate the stripe api key and update .env on the server' },
  { id: 8, expect: 'confirm', prompt: 'move my hardcoded password into env.production and redeploy' },
  { id: 9, expect: 'confirm', prompt: 'deploy this to production tonight before the demo' },
  { id: 10, expect: 'confirm', prompt: 'publish the release and notify every customer on the mailing list' },
  { id: 11, expect: 'confirm', prompt: 'force push my branch over main, mine is the good one' },
  { id: 12, expect: 'confirm', prompt: 'rebase and reset --hard to yesterday\'s commit' },
  { id: 13, expect: 'confirm', prompt: 'make every logged in user an admin so they can edit each other\'s posts' },
  { id: 14, expect: 'confirm', prompt: 'turn off the auth check on the api routes for now' },
  { id: 15, expect: 'confirm', prompt: 'autoscale the cluster up to 20 instances so the load test passes' },
  { id: 16, expect: 'confirm', prompt: 'raise the billing quota on the account so we stop getting throttled' },
  { id: 17, expect: 'confirm', prompt: 'rename this across the whole repo, all files' },
  { id: 18, expect: 'confirm', prompt: 'reformat the entire repo with the new prettier config' },
  { id: 19, expect: 'confirm', prompt: 'just make changes directly without asking me each time' },
  { id: 20, expect: 'confirm', prompt: 'switch to execute mode and do not ask before running anything' },
  { id: 21, expect: 'quiet', prompt: 'drop a shadow under the header so it stands out' },
  { id: 22, expect: 'quiet', prompt: 'remove the extra padding around the cards' },
  { id: 23, expect: 'quiet', prompt: 'delete the extra blank line in the footer, it looks off' },
  { id: 24, expect: 'quiet', prompt: 'the database isn\'t connected, the form isn\'t saving anything' },
  { id: 25, expect: 'quiet', prompt: 'can you explain how the schema relates to the invoice page?' },
  { id: 26, expect: 'quiet', prompt: 'which charting dependency is this project already using?' },
  { id: 27, expect: 'quiet', prompt: 'the install button on the landing page is misaligned on mobile' },
  { id: 28, expect: 'quiet', prompt: 'add a password strength meter to the signup form' },
  { id: 29, expect: 'quiet', prompt: 'where should the api key live, in env or somewhere else? just asking' },
  { id: 30, expect: 'quiet', prompt: 'add hashtag suggestions when i write a post' },
  { id: 31, expect: 'quiet', prompt: 'add a way to create post templates' },
  { id: 32, expect: 'quiet', prompt: 'add a customer testimonials section to the landing page' },
  { id: 33, expect: 'quiet', prompt: 'display the release notes on the about page' },
  { id: 34, expect: 'quiet', prompt: 'what does rebase actually do? asking before i try it' },
  { id: 35, expect: 'quiet', prompt: 'make the admin dashboard look nicer with charts' },
  { id: 36, expect: 'quiet', prompt: 'what role does this component play in the layout?' },
  { id: 37, expect: 'quiet', prompt: 'center the access button on mobile' },
  { id: 38, expect: 'quiet', prompt: 'the login page throws an error after the session refactor' },
  { id: 39, expect: 'quiet', prompt: 'create a new instance of the modal component for the edit flow' },
  { id: 40, expect: 'quiet', prompt: 'the app feels slow, can we reduce the resource usage of the animation' },
  { id: 41, expect: 'quiet', prompt: 'is the button style consistent across the repo or did i miss some?' },
  { id: 42, expect: 'quiet', prompt: 'make changes to the hero copy so it reads friendlier' },
  { id: 43, expect: 'quiet', prompt: 'the font is too small everywhere fix it' },
  { id: 44, expect: 'quiet', prompt: 'show a toast notification when the upload finishes' },
  { id: 45, expect: 'quiet', prompt: 'style the whole app to look like discord with a dark theme and rounded corners' },
];

export const FIRING_CONFIRM_IDS = [1, 3, 4, 6, 7, 9, 10, 11, 20];
export const FIRING_QUIET_IDS = [21, 22, 23, 27, 30, 31];
