// Generator + drift-guard for the browser-safe TF-IDF weight table.
//
// The browser cannot run `natural` (Node-only: node:module/createRequire + fs).
// Instead, we precompute — USING `natural` itself — the exact per-stage TF-IDF
// weight of every corpus term, and ship that table as static data
// (tfidf-model.generated.ts). The browser classifier then only tokenizes + sums,
// so its numbers are `natural`'s numbers by construction.
//
// This file does two jobs:
//   1. GENERATE: run with NEXPATH_GEN_TFIDF=1 to (re)write the generated table.
//   2. DRIFT-GUARD (always): recompute the table from the current TRAINING_DATA
//      and assert the committed file matches — so if the corpus ever changes,
//      CI fails until the table is regenerated. This is what keeps the browser
//      classifier from silently diverging from the CLI's.

import { describe, it, expect } from 'vitest';
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { TRAINING_DATA } from '../../classifier/TFIDFClassifier.js';
import { STAGES } from './types.js';

const _require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const { TfIdf } = _require('natural') as { TfIdf: new () => any };

const GENERATED_PATH = join(dirname(fileURLToPath(import.meta.url)), 'tfidf-model.generated.ts');

/** Recompute the per-stage {term: tf*idf} table straight from `natural`. */
function computeWeights(): Record<string, Record<string, number>> {
  const tfidf = new TfIdf();
  for (const stage of STAGES) tfidf.addDocument(TRAINING_DATA[stage].join(' '));

  const weights: Record<string, Record<string, number>> = {};
  STAGES.forEach((stage, i) => {
    const doc = tfidf.documents[i] as Record<string, number>;
    const stageWeights: Record<string, number> = {};
    for (const term of Object.keys(doc)) {
      if (term === '__key') continue;
      // natural's tfidf([term], i) === tf(term, doc_i) * idf(term) — the exact
      // per-doc contribution the query path accumulates for this term.
      stageWeights[term] = tfidf.tfidf([term], i) as number;
    }
    weights[stage] = stageWeights;
  });
  return weights;
}

/** Deterministic TS module text — stages in STAGES order, terms sorted. */
function serialize(weights: Record<string, Record<string, number>>): string {
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by tfidf-model.gen.test.ts — DO NOT EDIT BY HAND.');
  lines.push('// Regenerate with: NEXPATH_GEN_TFIDF=1 npx vitest run src/core/classifier/tfidf-model.gen.test.ts');
  lines.push('//');
  lines.push('// Per-stage TF-IDF weights (tf*idf), precomputed from src/classifier/TFIDFClassifier.ts');
  lines.push("// TRAINING_DATA via `natural`. Keyed [stage][term]. Consumed by tfidf-browser.ts.");
  lines.push('');
  lines.push("import type { Stage } from './types.js';");
  lines.push('');
  lines.push('export const TFIDF_WEIGHTS: Record<Stage, Record<string, number>> = {');
  for (const stage of STAGES) {
    const stageWeights = weights[stage];
    const terms = Object.keys(stageWeights).sort();
    lines.push(`  ${stage}: {`);
    for (const term of terms) {
      lines.push(`    ${JSON.stringify(term)}: ${stageWeights[term]},`);
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  return lines.join('\n');
}

describe('tfidf-model generated table', () => {
  it('committed tfidf-model.generated.ts matches the corpus (regenerate with NEXPATH_GEN_TFIDF=1 if this fails)', () => {
    const expected = serialize(computeWeights());

    if (process.env.NEXPATH_GEN_TFIDF === '1') {
      writeFileSync(GENERATED_PATH, expected, 'utf8');
    }

    expect(existsSync(GENERATED_PATH)).toBe(true);
    // Windows checkouts with core.autocrlf rewrite the committed file to CRLF; the table, not the EOL, is the pin.
    const actual = readFileSync(GENERATED_PATH, 'utf8').replace(/\r\n/g, '\n');
    expect(actual).toBe(expected);
  });
});
